---
title: "ECO 395M: Exercises 2"
author: "Blake (Pin Yun) Lin and Jayme Gerring"
date: "3/7/2022"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
````
#importing 
library(tidyverse)
library(ggplot2)
library(rsample)  
library(caret)
library(modelr)
library(parallel)
library(foreach)
library(lubridate)

```
## Problem 1: Data visualization: Capital Metro

###Part A: 

```{r 1A,  message=FALSE, echo=FALSE}

#reading in the CSV

capmetro_UT <- read.csv("/Users/jaymegerring/Downloads/GitHub/ECO395M-1/data/capmetro_UT.csv")

# Recode the categorical variables in sensible, rather than alphabetical, order
capmetro_UT = mutate(capmetro_UT,
                     day_of_week = factor(day_of_week,
                                          levels=c("Mon", "Tue", "Wed","Thu", "Fri", "Sat", "Sun")),
                     month = factor(month,
                                    levels=c("Sep", "Oct","Nov")))

#calculate averages based on group

group_cols <- c("hour_of_day", "day_of_week", "month")
capmetro_UT_Adjusted<- capmetro_UT %>% 
  group_by(across(all_of(group_cols))) %>% 
  summarize(mean_boarding = mean(boarding))

#plotting the data!

ggplot(data= capmetro_UT_Adjusted, aes(x= hour_of_day, y = mean_boarding, colour = month, group = month)) + 
  geom_line() + facet_wrap(~day_of_week, scales='free') + 
  scale_x_continuous(limits=c(6,21)) + scale_y_continuous(limits=c(0,160)) +
  ggtitle("Average Boardings by Hour") + 
  labs(y = "Average Boardings", x = "Hour") + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  guides(color = guide_legend(title="Month"))

```
Average boardings during the months of September through November, organized by weekday 



```{r 1B,  message=FALSE, echo=FALSE}

#Adding a variable for minute intervals
capmetro_UT = mutate(capmetro_UT, intervals = 60*hour(timestamp) + minute(timestamp))

ggplot(capmetro_UT, aes(x = temperature , y = boarding  , color = weekend,
               shape = weekend)) + 
  geom_point(size = 2) + facet_wrap(~hour_of_day, scales = 'free') + 
  scale_x_continuous(limits=c(0,98)) + 
  scale_y_continuous(limits=c(0,290)) +
  ggtitle("Boardings By Temperature and Hour") +
  labs(y = "Boardings", x = "Temperature (ºF)") + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  scale_shape_discrete(labels = c("Weekday", "Weekend")) +
  scale_colour_discrete(labels = c("Weekday", "Weekend")) +
  labs(shape = "Day of the Week", colour = "Day of the Week")
  ```
  
  
 
  

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
